name: fade_out_particle
description: Fade out particle effect for disappearing views like Text and Icon
version: 1.2.1
homepage: https://github.com/hoomanmmd/fade_out_particle

environment:
  sdk: ">=2.17.0-182.1.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0

flutter: